spring:
  application:
    name: gate-server

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  eureka:
    enabled: true

server:
  port: 8602

#日志
logging:
  path: classpath:log4j2.yml
zuul:
  sensitive-headers:
  strip-prefix: true
  routes:
    provider:
    #这个url参数只是用在没有用注册中心的时候,仅仅是zuul路由到要去模块,从而直接指定的
#      url: http://localhost:8603
      path: /provider/**
      serviceId: provider
    consumer:
          path: /consumer/**
          serviceId: consumer


#关闭超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8601/eureka/
  instance:
    # 租期更新时间间隔（默认30秒）
    leaseRenewalIntervalInSeconds: 15
    # 租期到期时间（默认90秒）
    leaseExpirationDurationInSeconds: 30
    prefer-ip-address: true
    # 指定此客户端的ip
    ip-address: ${spring.cloud.client.ipAddress}




