spring:
  application:
    name: eureka-server

ribbon:
  eureka:
    enabled: true


server:
  port: 8601

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  server:
    enable-self-preservation: false # 设为false，关闭自我保护
    ## 清理时间间隔，单位毫秒，默认是60*1000）
    evictionIntervalTimerInMs: 30000
  client:
    ## 是否将自己注册到Eureka Server，默认为true。由于当前这个应用就是Eureka Server，故而设为false
    registerWithEureka: false
    ## 是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false
    fetchRegistry: false
    ## 与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# 日志
logging:
  path: classpath:log4j2.yml

